### 
# 请求 repos
# see: https://docs.github.com/en/graphql/reference/objects#repositoryconnection
POST https://api.github.com/graphql
Authorization: bearer 【填入 token】
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  viewer {
    repositories(
      first: 10
      orderBy: {
      # 按星星数量，倒序
        direction: DESC
      	field: CREATED_AT
    }) {
      # edges {
      #   cursor
      #   node {
      #     id
      #   }
      # }
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
  		nodes {
        name
        description
        url
      }
    }
  }
}

###
# 请求 star repos
# see: https://docs.github.com/en/graphql/reference/objects#starredrepositoryconnection

POST https://api.github.com/graphql
Authorization: bearer 【填入 token】
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query { 
  viewer {
    starredRepositories(
      first: 10
      orderBy: {
        field: STARRED_AT,
        direction: DESC
      }
    ) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        # 仓库名称
        name
        # 仓库地址
        url
        # 仓库描述
        description
        # 仓库的 owner
        owner {
          # 用户名称
          login
          # 用户首页地址
          url
        }
      }
    }
  }
}

###
# 请求 follow 的 users
# see: https://docs.github.com/en/graphql/reference/objects#followingconnection

POST https://api.github.com/graphql
Authorization: bearer 【填入 token】
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query { 
  viewer {
    following(
      first: 10
    ) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
				# 个性签名
        bio
        # 昵称         
        name
        # 出现在 url 上的名称
        login
        url
        itemShowcase {
					# 返回 pinned 仓库/gist 或者 popular 仓库
          items(first: 6) {
            totalCount
            nodes {
              ... on Repository {
                description
                name
                url
                stargazerCount
              }
            }
          }
        }
      }
    }
  }
}