### 
# 请求 repos
# see: https://docs.github.com/en/graphql/reference/objects#repositoryconnection
POST https://api.github.com/graphql
Authorization: bearer 【填入 token】
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  viewer {
    repositories(
      first: 10
      orderBy: {
        direction: ASC
        field: CREATED_AT
      }
    ) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        name
        description
        isPrivate
        isFork
        stargazerCount
        url
        createdAt
      }
    }
  }
}

###
# 请求 star repos
# see: https://docs.github.com/en/graphql/reference/objects#starredrepositoryconnection

POST https://api.github.com/graphql
Authorization: bearer 【填入 token】
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  viewer {
    starredRepositories(
      first: 10
      orderBy: {
        field: STARRED_AT
        direction: ASC
      }
    ) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        starredAt
        cursor
      }
      nodes {
        name
        url
        description
        owner {
          login
          url
        }
      }
    }
  }
}

###
# 请求 follow 的 users
# see: https://docs.github.com/en/graphql/reference/objects#followingconnection

POST https://api.github.com/graphql
Authorization: bearer 【填入 token】
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  viewer {
    following(
      first: 10
    ) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        bio
        name
        login
        url
        itemShowcase {
					# 返回 pinned 仓库/gist 或者 popular 仓库
          items(first: 6) {
            totalCount
            nodes {
              ... on Repository {
                description
                name
                url
                stargazerCount
              }
            }
          }
        }
      }
    }
  }
}